version: '3.9'
services: 
  web: 
    build: web
    ports: 
      - '7077:80'
    tty: true
    depends_on: 
      - mysql
  mysql: 
    build: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: res
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Redlock
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci